apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: claude-coding-no-sandbox-agent
  namespace: kagent
spec:
  description: Claude Code Agent - No Sandbox
  type: BYO
  byo:
    deployment:
      image: ghcr.io/the-mentor/kagent-claude-byo-agent:latest
      imagePullPolicy: Always
      env:
        - name: PORT
          value: "8080" # Regular Agents require A2A on port 8080 not port 80 so we override it via environment variable.
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: anthropic-credentials
              key: ANTHROPIC_API_KEY
        # - name: ANTHROPIC_BASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: anthropic-credentials
        #       key: ANTHROPIC_BASE_URL
        - name: LOG_LEVEL
          value: "DEBUG"
